"""add cloudinary media metadata

Revision ID: 25e19c41cde5
Revises: 5875dcca3842
Create Date: 2026-10-04 22:52:38.785624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e19c41cde5'
down_revision = '5875dcca3842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('resource_type', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('duration_seconds', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_content_media_public_id'), ['public_id'], unique=False)

    with op.batch_alter_table('creator_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_public_id', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('intro_reel_public_id', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('intro_reel_thumbnail_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creator_profiles', schema=None) as batch_op:
        batch_op.drop_column('intro_reel_thumbnail_url')
        batch_op.drop_column('intro_reel_public_id')
        batch_op.drop_column('profile_image_public_id')

    with op.batch_alter_table('content_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_media_public_id'))
        batch_op.drop_column('height')
        batch_op.drop_column('width')
        batch_op.drop_column('duration_seconds')
        batch_op.drop_column('resource_type')
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
