"""Stage 1 creator platform foundation

Revision ID: 296e9c4d1410
Revises: 
Create Date: 2026-10-04 22:10:23.707266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296e9c4d1410'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_categories_slug'), ['slug'], unique=True)

    op.create_table('creator_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('intro_reel_url', sa.Text(), nullable=True),
    sa.Column('instagram_url', sa.Text(), nullable=True),
    sa.Column('tiktok_url', sa.Text(), nullable=True),
    sa.Column('youtube_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creator_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_profiles_username'), ['username'], unique=True)

    op.create_table('email_subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('unsubscribe_token', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unsubscribe_token'),
    sa.UniqueConstraint('verification_token')
    )
    with op.batch_alter_table('email_subscribers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_subscribers_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_subscribers_status'), ['status'], unique=False)

    op.create_table('content_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=30), nullable=False),
    sa.Column('access_level', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['content_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_posts_access_level'), ['access_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_posts_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_posts_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_posts_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_posts_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_content_posts_status'), ['status'], unique=False)

    op.create_table('content_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('media_url', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('media_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['content_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_media_post_id'), ['post_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_media_post_id'))

    op.drop_table('content_media')
    with op.batch_alter_table('content_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_posts_status'))
        batch_op.drop_index(batch_op.f('ix_content_posts_slug'))
        batch_op.drop_index(batch_op.f('ix_content_posts_published_at'))
        batch_op.drop_index(batch_op.f('ix_content_posts_content_type'))
        batch_op.drop_index(batch_op.f('ix_content_posts_category_id'))
        batch_op.drop_index(batch_op.f('ix_content_posts_access_level'))

    op.drop_table('content_posts')
    with op.batch_alter_table('email_subscribers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_subscribers_status'))
        batch_op.drop_index(batch_op.f('ix_email_subscribers_email'))

    op.drop_table('email_subscribers')
    with op.batch_alter_table('creator_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creator_profiles_username'))

    op.drop_table('creator_profiles')
    with op.batch_alter_table('content_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_categories_slug'))

    op.drop_table('content_categories')
    # ### end Alembic commands ###
