"""add cloudinary media metadata

Revision ID: 486565da0bd1
Revises: 507de127591d
Create Date: 2026-10-05 01:18:33.363849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486565da0bd1'
down_revision = '507de127591d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('email_type', sa.String(length=50), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['content_posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['email_subscribers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_deliveries_email_type'), ['email_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_deliveries_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_deliveries_recipient_email'), ['recipient_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_deliveries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_deliveries_subscriber_id'), ['subscriber_id'], unique=False)

    with op.batch_alter_table('email_subscribers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.alter_column('unsubscribe_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_email_subscribers_unsubscribe_token'), ['unsubscribe_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_subscribers_verification_token'), ['verification_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_subscribers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_subscribers_verification_token'))
        batch_op.drop_index(batch_op.f('ix_email_subscribers_unsubscribe_token'))
        batch_op.alter_column('unsubscribe_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('email_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_deliveries_subscriber_id'))
        batch_op.drop_index(batch_op.f('ix_email_deliveries_status'))
        batch_op.drop_index(batch_op.f('ix_email_deliveries_recipient_email'))
        batch_op.drop_index(batch_op.f('ix_email_deliveries_post_id'))
        batch_op.drop_index(batch_op.f('ix_email_deliveries_email_type'))

    op.drop_table('email_deliveries')
    # ### end Alembic commands ###
